export const fontOptions = [
    { name: 'Inter', value: "'Inter', sans-serif" },
    { name: 'Roboto', value: "'Roboto', sans-serif" },
    { name: 'Courier Prime', value: "'Courier Prime', monospace" },
    { name: 'Lobster', value: "'Lobster', cursive" },
    { name: 'Arial', value: "'Arial', sans-serif" },
    { name: 'Georgia', value: "'Georgia', serif" },
    { name: 'Open Sans', value: "'Open Sans', sans-serif" },
    { name: 'Montserrat', value: "'Montserrat', sans-serif" },
    { name: 'Oswald', value: "'Oswald', sans-serif" },
    { name: 'Lato', value: "'Lato', sans-serif" },
    { name: 'Playfair Display', value: "'Playfair Display', serif" },
    { name: 'Raleway', value: "'Raleway', sans-serif" },
    { name: 'Ubuntu', value: "'Ubuntu', sans-serif" },
    { name: 'PT Sans', value: "'PT Sans', sans-serif" },
    { name: 'Nunito', value: "'Nunito', sans-serif" },
    { name: 'Merriweather', value: "'Merriweather', serif" },
    { name: 'Fira Sans', value: "'Fira Sans', sans-serif" },
    { name: 'Quicksand', value: "'Quicksand', sans-serif" },
    { name: 'Pacifico', value: "'Pacifico', cursive" },
    { name: 'Rubik', value: "'Rubik', sans-serif" },
    { name: 'Source Sans Pro', value: "'Source Sans Pro', sans-serif" },
    { name: 'Signika', value: "'Signika', sans-serif" },
    { name: 'Comfortaa', value: "'Comfortaa', sans-serif" },
    { name: 'Arvo', value: "'Arvo', serif" },
    { name: 'Cabin', value: "'Cabin', sans-serif" },
    { name: 'Exo 2', value: "'Exo 2', sans-serif" },
    { name: 'PT Serif', value: "'PT Serif', serif" },
    { name: 'Varela Round', value: "'Varela Round', sans-serif" },
    { name: 'Abril Fatface', value: "'Abril Fatface', cursive" },
    { name: 'Orbitron', value: "'Orbitron', sans-serif" },
    { name: 'Bangers', value: "'Bangers', cursive" },
    { name: 'Press Start 2P', value: "'Press Start 2P', cursive" },
    { name: 'Monoton', value: "'Monoton', cursive" },
    { name: 'Cinzel', value: "'Cinzel', serif" },
    { name: 'Black Ops One', value: "'Black Ops One', cursive" },
    { name: 'Fredericka the Great', value: "'Fredericka the Great', cursive" },
    { name: 'Luckiest Guy', value: "'Luckiest Guy', cursive" },
    { name: 'Permanent Marker', value: "'Permanent Marker', cursive" },
    { name: 'Special Elite', value: "'Special Elite', cursive" },
    { name: 'Unica One', value: "'Unica One', sans-serif" },
    { name: 'Major Mono Display', value: "'Major Mono Display', monospace" },
    { name: 'Faster One', value: "'Faster One', cursive" },
    { name: 'Codystar', value: "'Codystar', cursive" },
    { name: 'VT323', value: "'VT323', monospace" }
];

export function formatTime(num) {
    return num.toString().padStart(2, '0');
}

